name: Staging deployment

on: 
  pull_request:
    types: [labeled]
    
jobs:
  build:
    runs-on: ubuntu-latest
#     if is the conditional to see if the job will run
    if: contains(github.event.pull_request.labels.*.name, 'stage')
